# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LilAmore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LilAmore
    pod 'Firebase/Core'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'LilAmoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
